export type Applicant = {
  id: string;
  name: string;
  role: string;
  city: string;
  state: string;
  zip: string;
  years: number;
  skills: string[];
  payBand: string;
  insurance: string;
  vehicle: string;
  certs: string;
  about: string;
  status: "Ready to apply" | "Applied — pending" | "Docs in" | "Academy passed";
};

export const APPLICANTS: Applicant[] = [
  {
    id: "APP-01",
    name: "Marcus Hale",
    role: "Mobile brakes / general",
    city: "Charlotte",
    state: "NC",
    zip: "28213",
    years: 11,
    skills: ["Brakes", "Oil / fluids", "Roadside"],
    payBand: "ICE L2 — $38",
    insurance: "GL + garagekeepers + commercial auto on file",
    vehicle: "2019 Transit with lift and impact set",
    certs: "ASE A5 brakes",
    about: "University City. Wants driveway brake work after 4pm. No EV HV.",
    status: "Docs in",
  },
  {
    id: "APP-02",
    name: "Alicia Nguyen",
    role: "EV / hybrid",
    city: "Charlotte",
    state: "NC",
    zip: "28262",
    years: 7,
    skills: ["EV / HV", "EV 12V", "Scan / PMI"],
    payBand: "EV-1 — $35",
    insurance: "GL + garagekeepers. Policy allows EV.",
    vehicle: "2021 Sprinter, CAT III meter, class-0 gloves in date",
    certs: "ASE xEV1, Ford HV safety",
    about: "Will not open a crash pack. Good for 12V and isolated HV diag.",
    status: "Academy passed",
  },
  {
    id: "APP-03",
    name: "Jamal Price",
    role: "No-start / diagnostics",
    city: "Charlotte",
    state: "NC",
    zip: "28206",
    years: 9,
    skills: ["No-start", "Scan / PMI", "Roadside"],
    payBand: "ICE L2 — $38",
    insurance: "GL only — garagekeepers missing",
    vehicle: "F-150 with Snap-on Zeus and jump pack",
    certs: "ASE A6, A8",
    about: "Strong electrical. Cannot take jobs until garagekeepers is on the COI.",
    status: "Applied — pending",
  },
  {
    id: "APP-04",
    name: "Sofia Alvarez",
    role: "Tint installer",
    city: "Raleigh",
    state: "NC",
    zip: "27609",
    years: 6,
    skills: ["Tint"],
    payBand: "ICE L1 — $22",
    insurance: "GL on file.",
    vehicle: "Cargo van, mobile heat lamps, plotter",
    certs: "Film brand silver installer",
    about: "Triangle market. Service stays closed until two more Raleigh vendors qualify.",
    status: "Docs in",
  },
  {
    id: "APP-05",
    name: "Derrick Boone",
    role: "Detail + light paint",
    city: "Columbia",
    state: "SC",
    zip: "29210",
    years: 8,
    skills: ["Detailing"],
    payBand: "ICE L1 — $22",
    insurance: "GL + commercial auto",
    vehicle: "Trailer with water tank and extractor",
    certs: "Ceramic brand certified",
    about: "Midlands SC. Waiting on a second qualified vendor before customer launch.",
    status: "Ready to apply",
  },
  {
    id: "APP-06",
    name: "Priya Shah",
    role: "Shop bay lead",
    city: "Charlotte",
    state: "NC",
    zip: "28213",
    years: 14,
    skills: ["Brakes", "No-start", "Scan / PMI", "Oil / fluids"],
    payBand: "ICE L3 — $55",
    insurance: "On Speedy shop policy when in the bay",
    vehicle: "Works McDaniel Lane bay 1",
    certs: "ASE Master A1–A8",
    about: "Wants in-shop tickets, not highway roadside.",
    status: "Academy passed",
  },
  {
    id: "APP-07",
    name: "Chris Lang",
    role: "Golf cart kits",
    city: "Atlanta",
    state: "GA",
    zip: "30318",
    years: 5,
    skills: ["Golf cart kits", "Oil / fluids"],
    payBand: "ICE L1 — $22",
    insurance: "GL + garagekeepers",
    vehicle: "Flatbed trailer and lift table",
    certs: "Club Car / EZ-GO kit schools",
    about: "Atlanta waitlist. Carts only. City stays dark until a full bench exists.",
    status: "Applied — pending",
  },
  {
    id: "APP-08",
    name: "Keisha Rowan",
    role: "Roadside / lockout / jump",
    city: "Nashville",
    state: "TN",
    zip: "37209",
    years: 4,
    skills: ["Roadside", "Oil / fluids"],
    payBand: "ICE L1 — $22 + $25 after hours",
    insurance: "GL + commercial auto.",
    vehicle: "Night-shift van, lockout kit, pack",
    certs: "Academy Standards in progress",
    about: "Music City waitlist. After-hours only.",
    status: "Ready to apply",
  },
  {
    id: "APP-09",
    name: "Omar Haddad",
    role: "EV specialist",
    city: "Dallas",
    state: "TX",
    zip: "75204",
    years: 10,
    skills: ["EV / HV", "Scan / PMI", "No-start"],
    payBand: "EV-3 — $75",
    insurance: "Full package, EV not excluded",
    vehicle: "Insulated tools, two glove sets, thermal camera",
    certs: "ASE xEV1 xEV2",
    about: "DFW waitlist. Pack-off stays at a shop, not a driveway.",
    status: "Docs in",
  },
  {
    id: "APP-10",
    name: "Hannah Cole",
    role: "Mobile general + brakes",
    city: "Concord",
    state: "NC",
    zip: "28027",
    years: 8,
    skills: ["Brakes", "Oil / fluids", "Detailing"],
    payBand: "ICE L2 — $38",
    insurance: "GL + garagekeepers + commercial auto",
    vehicle: "Ram Promaster, two-post portable lift",
    certs: "ASE A4 A5",
    about: "Concord is live off the Charlotte hub.",
    status: "Academy passed",
  },
];

export const ASSIGN_OPTIONS = [
  "Unassigned",
  "Shop bay 1",
  ...APPLICANTS.filter((p) => p.state === "NC" && ["Charlotte", "Concord"].includes(p.city)).map(
    (p) => `${p.name} — ${p.city} — ${p.payBand}`,
  ),
];
