export type Applicant = {
  id: string;
  name: string;
  role: string;
  zip: string;
  years: number;
  skills: string[];
  payBand: string;
  insurance: string;
  vehicle: string;
  certs: string;
  about: string;
  status: "Ready to apply" | "Applied — pending" | "Docs in" | "Academy passed";
};

export const APPLICANTS: Applicant[] = [
  {
    id: "APP-01",
    name: "Marcus Hale",
    role: "Mobile brakes / general",
    zip: "28213",
    years: 11,
    skills: ["Brakes", "Oil / fluids", "Roadside"],
    payBand: "ICE L2 — $38",
    insurance: "GL + garagekeepers + commercial auto on file",
    vehicle: "2019 Transit with lift and impact set",
    certs: "ASE A5 brakes",
    about: "University City. Wants driveway brake work after 4pm. No EV HV.",
    status: "Docs in",
  },
  {
    id: "APP-02",
    name: "Alicia Nguyen",
    role: "EV / hybrid",
    zip: "28262",
    years: 7,
    skills: ["EV / HV", "EV 12V", "Scan / PMI"],
    payBand: "EV-1 — $35",
    insurance: "GL + garagekeepers. Policy allows EV. Waiting commercial auto endorsement.",
    vehicle: "2021 Sprinter, CAT III meter, class-0 gloves in date",
    certs: "ASE xEV1, Ford HV safety",
    about: "Will not open a crash pack. Good for 12V and isolated HV diag.",
    status: "Academy passed",
  },
  {
    id: "APP-03",
    name: "Jamal Price",
    role: "No-start / diagnostics",
    zip: "28206",
    years: 9,
    skills: ["No-start", "Scan / PMI", "Roadside"],
    payBand: "ICE L2 — $38",
    insurance: "GL only — garagekeepers missing",
    vehicle: "F-150 with Snap-on Zeus and jump pack",
    certs: "ASE A6, A8",
    about: "Strong electrical. Cannot take jobs until garagekeepers is on the COI.",
    status: "Applied — pending",
  },
  {
    id: "APP-04",
    name: "Sofia Alvarez",
    role: "Tint installer",
    zip: "28205",
    years: 6,
    skills: ["Tint"],
    payBand: "ICE L1 — $22",
    insurance: "GL on file. No garagekeepers needed for glass-only if car stays in driveway.",
    vehicle: "Cargo van, mobile heat lamps, plotter",
    certs: "Film brand silver installer",
    about: "Legal NC shades only. Will not do windshields darker than the strip.",
    status: "Docs in",
  },
  {
    id: "APP-05",
    name: "Derrick Boone",
    role: "Detail + light paint",
    zip: "28215",
    years: 8,
    skills: ["Detailing"],
    payBand: "ICE L1 — $22",
    insurance: "GL + commercial auto",
    vehicle: "Trailer with water tank and extractor",
    certs: "Ceramic brand certified",
    about: "Interior + paint. Will not cut through failed clear.",
    status: "Ready to apply",
  },
  {
    id: "APP-06",
    name: "Priya Shah",
    role: "Shop bay lead",
    zip: "28213",
    years: 14,
    skills: ["Brakes", "No-start", "Scan / PMI", "Oil / fluids"],
    payBand: "ICE L3 — $55",
    insurance: "On Speedy shop policy when in the bay",
    vehicle: "Works McDaniel Lane bay 1",
    certs: "ASE Master A1–A8",
    about: "Wants in-shop tickets, not highway roadside.",
    status: "Academy passed",
  },
  {
    id: "APP-07",
    name: "Chris Lang",
    role: "Golf cart kits",
    zip: "28269",
    years: 5,
    skills: ["Golf cart kits", "Oil / fluids"],
    payBand: "ICE L1 — $22",
    insurance: "GL + garagekeepers",
    vehicle: "Flatbed trailer and lift table",
    certs: "Club Car / EZ-GO kit schools",
    about: "Neighborhood carts and HOA fleets. Not a car no-start tech.",
    status: "Applied — pending",
  },
  {
    id: "APP-08",
    name: "Keisha Rowan",
    role: "Roadside / lockout / jump",
    zip: "28216",
    years: 4,
    skills: ["Roadside", "Oil / fluids"],
    payBand: "ICE L1 — $22 + $25 after hours",
    insurance: "GL + commercial auto. Wants Agero later.",
    vehicle: "Night-shift van, lockout kit, pack",
    certs: "None yet — Academy Standards in progress",
    about: "Available after 6pm and Sunday. No brake installs.",
    status: "Ready to apply",
  },
  {
    id: "APP-09",
    name: "Omar Haddad",
    role: "EV specialist",
    zip: "28202",
    years: 10,
    skills: ["EV / HV", "Scan / PMI", "No-start"],
    payBand: "EV-3 — $75",
    insurance: "Full package, EV not excluded",
    vehicle: "Insulated tools, two glove sets, thermal camera",
    certs: "ASE xEV1 xEV2, Tesla aftermarket safety",
    about: "Uptown and south Charlotte. Pack-off work stays at a shop, not a driveway.",
    status: "Docs in",
  },
  {
    id: "APP-10",
    name: "Hannah Cole",
    role: "Mobile general + brakes",
    zip: "28027",
    years: 8,
    skills: ["Brakes", "Oil / fluids", "Detailing"],
    payBand: "ICE L2 — $38",
    insurance: "GL + garagekeepers + commercial auto",
    vehicle: "Ram Promaster, two-post portable lift",
    certs: "ASE A4 A5",
    about: "Concord / University overlap. Can take overflow when Marcus is full.",
    status: "Academy passed",
  },
];

export const ASSIGN_OPTIONS = ["Unassigned", "Shop bay 1", ...APPLICANTS.map((p) => `${p.name} — ${p.payBand}`)];
